upbound/xgql

cmd/xgql/main.go
Fixes https://github.com/upbound/xgql/issues/72
This commit adds a chi middleware that compresses certain content types (including the JSON returned by GraphQL queries) using gzip.
I have:
I've used the playground to make some queries and validated that the responses I get are gzipped.
=> Compress HTTP reponses

.github/workflows/ci.yml, .golangci.yml, Makefile, cmd/xgql/main.go, go.mod, internal/auth/auth.go
Use Go 1.19 to build xgql and address the issues revealed by updating to golangci-lint v1.49.0
I have:
Ran `make` and `make reviewable`
=> Use Go 1.19 to build xgql

README.md, cluster/local/service-account.yaml
Kubernetes used to do this automatically, but now you need to manually create a service account token secret. There's no way to do this using the CLI that I can find, so let's just create it using a YAML manifest.
https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
I have:
I've tested the flow on my laptop.
=> Create a token secret for our service account

.github/workflows/ci.yml, .github/workflows/promote.yml
Adds us-east-1 as default region for AWS operations.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
See https://github.com/upbound/universal-crossplane/pull/256 as example.
I have:
Verified with same change in other repos.
=> Add default AWS region to workflows

internal/graph/generated/generated.go, internal/graph/model/generated.go, internal/graph/resolvers/query.go, internal/graph/resolvers/query_test.go, schema/queries.gql
Add `xrmResourceTree` to get a list of all descendantes of a given XRM Resource.
Resovles #95
I have:
Ran `make` and `make reviewable`
=> Add `crossplaneResourceTree` to get a list of all descendantes of a given XRM Resource.

internal/graph/generated/generated.go, internal/graph/model/apiextensions.go, internal/graph/model/apiextensions_test.go, internal/graph/model/generated.go, internal/graph/resolvers/apiextensions.go, internal/graph/resolvers/apiextensions_test.go, schema/apiextensions.gql
Add ability to filter defined resources by ready status.
This can be done for defined XRCs and XRs on an XRD.
This also deprecates the existing filters and moves them to an "options" input argument.
Resolves #94
I have:
ran `make` and `make reviewable`
=> Add ability to filter defined resources by ready status.

cluster/charts/xgql/templates/deployment.yaml, cluster/charts/xgql/values.yaml.tmpl, cmd/xgql/main.go, internal/options.go, internal/request/formatter.go, internal/server/health/health.go, internal/server/health/server.go
- adds handlers for livez and readyz
- extends current deployment.yaml to enable liveness and readiness probes
I have:
1. Pushed local build to personal registry
2. Started a kind cluster
3. Updated values.yaml.tmpl to use the build docker image
4. Enabled debug logging within the deployment
5. `helm install xgql cluster/charts/xgql`
6. Verified the deployment recognized the liveness and readiness probes:
```
kubectl describe deploy xgql
Name:                   xgql
Namespace:              default
CreationTimestamp:      Wed, 14 Dec 2022 11:00:44 -0800
Labels:                 app=xgql
app.kubernetes.io/managed-by=Helm
chart=xgql-0.0.1
heritage=Helm
release=xgql
Annotations:            deployment.kubernetes.io/revision: 5
meta.helm.sh/release-name: xgql
meta.helm.sh/release-namespace: …
```
=> Introduce basic readyz and livez probes

Makefile, internal/graph/present/present.go, internal/graph/present/present_test.go
Prior to this change, client calls would typically see a number of error messages that could be gracefully handled by the client if they included additional context.
For example:
- non APIStatus timeouts 
- non APIStatus connection resets when communicating with the API server
- queries that would generally return a NoMatchKind or NoMatchResource
each of these errors would return a source `Unknown`.
This changeset:
- introduce new NOT_FOUND_ERROR  code
- introduce new RETRYABLE_ERROR code
- represent NoMatchKind and NoMatchResource differently so clients can distinguish between the two
Clients are now able to:
- distinguish INTERNAL_SERVER_ERROR from NOT_FOUND_ERRORs
- be signaled that the error they received is retryable when receiving the RETRYABLE_ERROR code.
I have:
New unit tests. …
=> Extend error presentation to account for other error types

cluster/charts/xgql/values.yaml.tmpl, cmd/xgql/main.go
Raise the cache timeout to reduce cold cache.
This is a tradeoff that keeps the cache alive much longer at the cost of memory and cpu.
I have:
=> Raise the cache timeout to reduce cold cache.

internal/graph/resolvers/composite.go, internal/graph/resolvers/composite_test.go
Handle cases where CompositeResource.ResourceReferences has entries with no name by ignoring them.
I have:
Verified locally and with unit tests that when CompositeResource.ResourceReferences contained entries with no name (i.e. name == "") we just ignore that ref.
=> Handle cases where CompositeResource.ResourceReferences has entries with no name

cmd/xgql/main.go, go.mod, go.sum, internal/graph/model/apiextensions.go, internal/graph/model/common.go, internal/graph/model/common_test.go, internal/graph/model/composite.go, internal/graph/model/managed.go, internal/graph/model/providerconfig.go, internal/graph/model/util.go, internal/graph/resolvers/apiextensions.go, internal/graph/resolvers/apiextensions_test.go, internal/graph/resolvers/common_test.go, internal/graph/resolvers/managed.go, internal/graph/resolvers/managed_test.go, internal/graph/resolvers/mutation.go, internal/graph/resolvers/mutation_test.go, internal/graph/resolvers/objectmeta_test.go, internal/graph/resolvers/provider.go, internal/graph/resolvers/provider_test.go, internal/graph/resolvers/providerconfig.go, internal/graph/resolvers/providerconfig_test.go, internal/graph/resolvers/query.go, internal/graph/resolvers/query_test.go, internal/unstructured/customresourcedefinition.go
This is a follow on to https://github.com/upbound/xgql/pull/114.
With the changes from #114, we saw that following resource utilization graphs (notably much better than prior to the change):
However as seen in the heap pprof after the fix:
There's memory consumption occurring in `JSONSchemaProps*`. As referenced in #114, we've seen high utilization when un/marshaling `CustomResourceDefinition`s; much of this comes from how expensive it is to process the `JSONSchemaProps*`. Fortunately, these pieces are necessary for producing the `CustomResource` Validators - which is unnecessary for `xgql`.
With that in mind, this PR moves to using `Unstructured` instead of the full `CustomResourceDefinition` types. With just that adjustment we see the following differences:
Heap pprof:
Utilization …
=> Move to using unstructured.Unstructured rather than extv1.CustomResourceDefinition

cmd/xgql/main.go, internal/clients/clients.go, internal/graph/model/common.go, internal/graph/resolvers/provider.go, internal/graph/resolvers/provider_test.go
- It looks like unstructured.Unstructured calls are not being cached. This is resulting in this more expensive query timing out and failing.
- Moving back to CRDs as a near term workaround until we can determine why Unstructured is not being cached.
I have:
1. make build test
2. Performed a query that resulted in all CRDs being looked up. Noted that query time was 5 seconds with a cold cache, 1 second with a warm cache, compared to the query timing out previously.
=> Move ProviderRevisionStatus Objects back to using CRDs

cmd/xgql/main.go, go.mod, go.sum, internal/auth/auth.go, internal/clients/live_query.go, internal/graph/extensions/live_query/json_patch.go, internal/graph/extensions/live_query/live_query.go, internal/graph/extensions/live_query/runtime.go
Signed-off-by: Bulat Shakirzyanov <83289+avalanche123@users.noreply.github.com>
- fix live query condition in informer listener.
- add blocking wait while waiting for live query notifications.
- fix json path generation to handle cases of object moved and modified.
I have:
Testing it on a local cluster.
=> live query fixes

internal/auth/auth.go
During websocket initialization we overwrote auth context populated from the
request middleware. This is necessary when using the playground as browsers
send only a limited subset of headers when initializing a websocket connection.
However, for programmatic websocket clients that do send auth headers in the
initial upgrade request, the websocket init function was clearing those from
context.
This PR makes auth context initialization from the websocket connection init
function conditional and only runs if auth context wasn't already initialized.
I have:
I'm testing this locally with a programmatic websocket client.
=> skip websocket auth init if initialized

internal/clients/clients.go, internal/clients/clients_test.go
Simplify client - extend expiry on get, and don't wrap client in session.
I have:
Tested locally.
=> unwrap client

cmd/xgql/main.go, go.mod, go.sum, internal/cache/bbolt_cache.go, internal/cache/bbolt_cache_test.go, internal/cache/bbolt_wrapper.go, internal/cache/cleaner.go, internal/cache/cleaner_test.go, internal/clients/clients.go, internal/graph/resolvers/apiextensions.go, internal/graph/resolvers/query.go, internal/graph/resolvers/query_test.go
- Update dependency versions.
- Added a new cache wrapper that:
- Stores full objects in a bolt database on disk.
- Clears object fields using a cache.TransformFunc.
- Enriches objects with data from disk before returning.
I have:
Launched this patched version on an MCP and verified results.
=> minimize memory requirements of informer cache

cmd/xgql/main.go
The `RequestId` middleware was missing. So the log never had a request-id.
Tested locally.
=> Read request-id from header

cmd/xgql/main.go, internal/clients/clients.go
With `-d -d -d -d -d -d` client-go logs requests. So one can actually see what xgql is doing behind the scenes and why requests take long.
Tested locally:
=> Turn --debug into a counter and set klog verbosity to its value

cmd/xgql/main.go, internal/cache/bbolt_cache.go, internal/cache/cleaner.go, internal/cache/cleaner_test.go
We are continously cleaning objects it seems. In `upbound/sttts-2000-claims` roughly 25-30 per second, despite no requests.
This PR makes that visible.
Test locally by running with the playground again upper controlplane.
=> bbolt-cache: debug log when cleaning objects, and throttle to once per 1s

cmd/xgql/main.go, internal/auth/auth.go, internal/auth/auth_test.go
- make hash generation for client-id deterministic
- remove bearertoken as that is regenerated every 90s
This fixes a problem we were seeing where the same requester was identified as different clients resulting in excess informer cache accumulation and unbounded heap growth.
I have:
Deployed the changes out to some Upbound control planes and verified (through logging) that the client cache remained small and that memory and cpu did not grow unbounded (via metrics).
=> Fix excess memory consumption

internal/clients/clients.go
We are caching clients with an expiry (default 30 mins). If a cilent is reused from the cache, we are extending the expiration by the expiry time.
Right now, we think that is causing xgql to extend the expiration of clients with expired tokens (seems likely) and resulting in failed requests for the same clients.
Fixes #
I have:
=> Do not extend cache on every request

cmd/xgql/main.go, internal/auth/auth.go, internal/auth/auth_test.go, internal/clients/clients.go, internal/clients/clients_test.go
This PR adds support for authenticating against the API server using the proxied user information set by an authenticating proxy. The headers set by the authenticating proxy are currently not parameterized and they are expected to be `X-Remote-User`, `X-Remote-Group` and `X-Remote-Extra-`. Currently, xgql does not authenticate the incoming request itself.
When using proxied user information, xgql needs to make requests to the API server using a TLS client certificate. The certificate and the key to be used can optionally be specified via the newly added `--tls-client-cert` and `--tls-client-key` command-line options, respectively. For backwards-compatibility purposes, these two parameters are both optional.
The PR also adds another optional command-line argument `client-ca-bundle`, which …
=> Add support for authenticating proxy
